name: Python package

on:
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: wizmer/run-tox@master
      with:
        python-version: ${{ matrix.python-version }}
